"""
Report Generator — converts a Site Scout result dict into a styled PDF.
Uses fpdf2 (already in requirements as fpdf2).
"""
import io
import re
from datetime import datetime
from fpdf import FPDF, XPos, YPos


# ── Colour palette ──────────────────────────────────────────────────────────────
NAVY  = (15,  30,  70)
TEAL  = (0,  130, 130)
WHITE = (255, 255, 255)
LGREY = (245, 245, 248)
DGREY = (80,  80,  90)
BLACK = (20,  20,  25)


class _PDF(FPDF):
    def __init__(self, top_city: str):
        super().__init__()
        self.top_city = top_city
        self.set_auto_page_break(auto=True, margin=18)

    # ── Header ──────────────────────────────────────────────────────────────────
    def header(self):
        # Navy bar
        self.set_fill_color(*NAVY)
        self.rect(0, 0, 210, 14, style="F")
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*WHITE)
        self.set_xy(8, 3)
        self.cell(0, 8, "Data Center Intelligence Platform  |  Site Scout Report", align="L")
        self.set_xy(0, 3)
        self.cell(202, 8, datetime.today().strftime("%d %b %Y"), align="R")
        self.ln(10)

    # ── Footer ──────────────────────────────────────────────────────────────────
    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*DGREY)
        self.cell(0, 6, f"Page {self.page_no()}  |  Confidential - generated by DC Intelligence Platform", align="C")


_UNICODE_MAP = str.maketrans({
    "\u2014": "--",   # em dash
    "\u2013": "-",    # en dash
    "\u2018": "'",    # left single quote
    "\u2019": "'",    # right single quote
    "\u201c": '"',    # left double quote
    "\u201d": '"',    # right double quote
    "\u2022": "*",    # bullet (replaced separately below)
    "\u2026": "...",  # ellipsis
    "\u00b0": " deg", # degree sign
    "\u00e9": "e",    # é
    "\u00e8": "e",    # è
    "\u00fc": "u",    # ü
    "\u00f6": "o",    # ö
})


def _strip_markdown(text: str) -> str:
    """Remove common markdown syntax and normalise unicode for latin-1 PDF."""
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"\*(.+?)\*",   r"\1", text)
    text = re.sub(r"`(.+?)`",     r"\1", text)
    text = re.sub(r"#{1,6}\s*",   "",    text)
    text = text.translate(_UNICODE_MAP)
    # Drop any remaining non-latin-1 characters
    text = text.encode("latin-1", errors="replace").decode("latin-1")
    return text.strip()


def _write_section(pdf: _PDF, title: str, body: str):
    """Render one named section with a teal heading bar + body text."""
    # Section heading
    pdf.set_fill_color(*TEAL)
    pdf.set_text_color(*WHITE)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 8, f"  {title}", fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(2)

    # Body — render line by line
    pdf.set_text_color(*BLACK)
    for raw_line in body.strip().splitlines():
        line = _strip_markdown(raw_line)
        if not line:
            pdf.ln(3)
            continue

        # Bullet points
        if line.startswith(("- ", "* ", "• ")):
            pdf.set_fill_color(*LGREY)
            pdf.set_font("Helvetica", "", 9)
            pdf.set_x(18)
            pdf.multi_cell(
                w=170, h=6,
                text=f"*  {line[2:]}",
                fill=True,
                new_x=XPos.LMARGIN, new_y=YPos.NEXT,
            )
        # Numbered items
        elif re.match(r"^\d+\.", line):
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_x(14)
            pdf.multi_cell(w=174, h=6, text=line, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        else:
            pdf.set_font("Helvetica", "", 9)
            pdf.set_x(14)
            pdf.multi_cell(w=174, h=6, text=line, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.ln(4)


def _parse_sections(report: str) -> dict[str, str]:
    """Split the markdown report into {section_title: body} pairs."""
    sections: dict[str, str] = {}
    current_title = "OVERVIEW"
    current_lines: list[str] = []

    for line in report.splitlines():
        if line.startswith("## "):
            if current_lines:
                sections[current_title] = "\n".join(current_lines).strip()
            current_title = line.lstrip("# ").strip()
            current_lines = []
        else:
            current_lines.append(line)

    if current_lines:
        sections[current_title] = "\n".join(current_lines).strip()

    return sections


def generate_pdf_report(result: dict) -> bytes:
    """
    Build a PDF from a run_site_scout() result dict.
    Returns raw PDF bytes suitable for st.download_button.
    """
    top_city = result.get("top_city", "See report")
    report   = result.get("report", "")
    reqs     = result.get("requirements", {})
    tools    = result.get("tools_used", [])

    pdf = _PDF(top_city=top_city)
    pdf.add_page()

    # ── Title block ─────────────────────────────────────────────────────────────
    pdf.set_fill_color(*LGREY)
    pdf.rect(8, 18, 194, 30, style="F")

    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(*NAVY)
    pdf.set_xy(12, 21)
    pdf.cell(0, 10, "Site Scout Analysis Report", align="L")

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(*TEAL)
    pdf.set_xy(12, 32)
    pdf.cell(0, 8, f"Top Recommended Site:  {top_city}", align="L")
    pdf.ln(22)

    # ── Requirements box ─────────────────────────────────────────────────────────
    if reqs:
        pdf.set_fill_color(*NAVY)
        pdf.set_text_color(*WHITE)
        pdf.set_font("Helvetica", "B", 9)
        pdf.cell(0, 7, "  SUBMITTED REQUIREMENTS", fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        pdf.set_fill_color(230, 235, 245)
        pdf.set_text_color(*DGREY)
        pdf.set_font("Helvetica", "", 9)
        pairs = [
            ("Region",           reqs.get("region", "—")),
            ("Capacity (MW)",    str(reqs.get("capacity_mw", "—"))),
            ("Renewable target", f"{reqs.get('renewable_pct', '—')}%+"),
            ("Budget tier",      reqs.get("budget_tier", "—")),
            ("Top priority",     reqs.get("priority", "—")),
        ]
        for label, value in pairs:
            pdf.set_x(14)
            pdf.cell(50, 6, f"{label}:", fill=False)
            pdf.cell(0,  6, value, fill=False, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(5)

    # ── Report sections ──────────────────────────────────────────────────────────
    sections = _parse_sections(report)

    SECTION_ORDER = [
        "RECOMMENDATION SUMMARY",
        "TOP 3 SITES RANKED",
        "WHY THIS BEATS THE ALTERNATIVES",
        "FIT WITH REQUIREMENTS",
        "RISKS & MITIGATIONS",
        "NEXT STEPS",
    ]

    for title in SECTION_ORDER:
        body = sections.get(title, "")
        if body:
            _write_section(pdf, title, body)

    # Any extra sections not in the canonical order
    for title, body in sections.items():
        if title not in SECTION_ORDER and title != "OVERVIEW" and body:
            _write_section(pdf, title, body)

    # ── Footer metadata ──────────────────────────────────────────────────────────
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 7)
    pdf.set_text_color(*DGREY)
    footer_text = _strip_markdown(
        f"Agent tools used: {', '.join(tools)}  |  "
        f"Generated: {datetime.today().strftime('%d %B %Y %H:%M')}  |  "
        "DC Intelligence Platform - AI-Powered Site Selection"
    )
    pdf.multi_cell(0, 5, footer_text, align="C")

    return bytes(pdf.output())
